/**
 * Core data model for the atlas.
 *
 * A note on honesty: every casualty figure in history is an estimate, and for most
 * of the last two thousand years it is a *contested* estimate. The model therefore
 * refuses to store a bare number — every figure carries a range and a confidence.
 * The UI renders that uncertainty rather than hiding it behind a single digit.
 */

export type Confidence = 'documented' | 'estimated' | 'disputed';

export interface CasualtyRange {
  low: number;
  best: number;
  high: number;
  confidence: Confidence;
}

/** One belligerent party. `members` lists constituent states where meaningful. */
export interface Side {
  name: string;
  members?: string[];
  military?: CasualtyRange;
  civilian?: CasualtyRange;
}

export type ConflictType =
  | 'interstate'
  | 'civil'
  | 'colonial'
  | 'religious'
  | 'genocide'
  | 'rebellion'
  | 'invasion';

export interface SourceRef {
  title: string;
  url?: string;
}

export interface Conflict {
  id: string;
  name: string;
  /** Inclusive years. Negative would be BCE; the shipped data starts at 0. */
  startYear: number;
  endYear: number;
  /** [lon, lat] — where the bubble sits. */
  centroid: [number, number];
  /** Approximate radius of the theatre in degrees, for the extent glow. */
  extent?: number;
  sides: Side[];
  total: CasualtyRange;
  type: ConflictType;
  region: string;
  summary?: string;
  sources: SourceRef[];
  /**
   * Id of a conflict whose total ALREADY INCLUDES this one's deaths.
   * The Holocaust and the Second Sino-Japanese War are both counted inside the
   * 70–85M usually quoted for WWII, so anything that sums deaths (the timeline
   * stream graph, era totals) must skip entries carrying this field or it will
   * double-count tens of millions of people. They still render on the map as
   * conflicts in their own right.
   */
  partOf?: string;
  /**
   * Per-locale overrides, keyed by locale code. Anything absent falls back to the
   * English fields above, so a partially translated language degrades to mixed
   * content rather than to blanks.
   */
  i18n?: Record<string, ConflictTranslation>;
}

export interface ConflictTranslation {
  name?: string;
  region?: string;
  summary?: string;
  /** Side names, in the same order as `sides`. */
  sides?: string[];
  /**
   * Translated member names, aligned with sides[i].members. Generated by the
   * compile step from data/curated/i18n/names.de.yaml — never hand-written
   * here. null for a side whose members are identical in this locale.
   */
  members?: (string[] | null)[];
}

/** A single dated, geolocated engagement. Sourced from Wikidata. */
export interface Battle {
  id: string;
  name: string;
  year: number;
  lon: number;
  lat: number;
  deaths?: number;
  conflictId?: string;
}

/** A named polity in a border snapshot. */
export interface BorderProps {
  name: string | null;
  subjectTo: string | null;
  /** The source dataset's own confidence in this boundary. Higher = fuzzier. */
  precision: number;
  /**
   * Stable entity id shared by the same polity across snapshots, assigned at
   * build time (pipeline/entities.ts). Purely visual continuity — tint, label
   * fades, selection persistence. null for unnamed/unclaimed land.
   */
  entity: number | null;
  /** Territory tint slot into theme.ts TERRITORY; null → plain MAP.land. */
  color: number | null;
  /** Label anchor [lon, lat]: pole of inaccessibility of the largest part. */
  labelAt: [number, number] | null;
  /** Spherical area in millionths of a steradian; label sizing/priority. */
  area: number;
}

export type VizMode = 'absolute' | 'population';

/** The polity under the cursor, as named by the border snapshot for that year. */
export interface HoveredCountry {
  name: string | null;
  subjectTo: string | null;
  /** Build-time entity id, for selection persistence across snapshots. */
  entity: number | null;
  /** [lon, lat] of the cursor, for the geographic "within the theatre" test. */
  at: [number, number];
}
